# Generated by Django 4.0.6 on 2022-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio/'),
            preserve_default=False,
        ),
    ]
