# Generated by Django 4.0.6 on 2022-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.CharField(blank=True, choices=[('I', 'In Stock'), ('O', 'Out Of Stock'), ('P', 'Pre Ordered')], max_length=2, null=True),
        ),
    ]
