# Generated by Django 4.0.6 on 2022-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('S', 'Shirts'), ('J', 'Jeans'), ('Sh', 'Shoes'), ('UX', 'Children')], max_length=2),
        ),
    ]
